	hps u0 (
		.hps_0_f2h_axi_slave_awid      (<connected-to-hps_0_f2h_axi_slave_awid>),      // hps_0_f2h_axi_slave.awid
		.hps_0_f2h_axi_slave_awaddr    (<connected-to-hps_0_f2h_axi_slave_awaddr>),    //                    .awaddr
		.hps_0_f2h_axi_slave_awlen     (<connected-to-hps_0_f2h_axi_slave_awlen>),     //                    .awlen
		.hps_0_f2h_axi_slave_awsize    (<connected-to-hps_0_f2h_axi_slave_awsize>),    //                    .awsize
		.hps_0_f2h_axi_slave_awburst   (<connected-to-hps_0_f2h_axi_slave_awburst>),   //                    .awburst
		.hps_0_f2h_axi_slave_awlock    (<connected-to-hps_0_f2h_axi_slave_awlock>),    //                    .awlock
		.hps_0_f2h_axi_slave_awcache   (<connected-to-hps_0_f2h_axi_slave_awcache>),   //                    .awcache
		.hps_0_f2h_axi_slave_awprot    (<connected-to-hps_0_f2h_axi_slave_awprot>),    //                    .awprot
		.hps_0_f2h_axi_slave_awvalid   (<connected-to-hps_0_f2h_axi_slave_awvalid>),   //                    .awvalid
		.hps_0_f2h_axi_slave_awready   (<connected-to-hps_0_f2h_axi_slave_awready>),   //                    .awready
		.hps_0_f2h_axi_slave_awuser    (<connected-to-hps_0_f2h_axi_slave_awuser>),    //                    .awuser
		.hps_0_f2h_axi_slave_wid       (<connected-to-hps_0_f2h_axi_slave_wid>),       //                    .wid
		.hps_0_f2h_axi_slave_wdata     (<connected-to-hps_0_f2h_axi_slave_wdata>),     //                    .wdata
		.hps_0_f2h_axi_slave_wstrb     (<connected-to-hps_0_f2h_axi_slave_wstrb>),     //                    .wstrb
		.hps_0_f2h_axi_slave_wlast     (<connected-to-hps_0_f2h_axi_slave_wlast>),     //                    .wlast
		.hps_0_f2h_axi_slave_wvalid    (<connected-to-hps_0_f2h_axi_slave_wvalid>),    //                    .wvalid
		.hps_0_f2h_axi_slave_wready    (<connected-to-hps_0_f2h_axi_slave_wready>),    //                    .wready
		.hps_0_f2h_axi_slave_bid       (<connected-to-hps_0_f2h_axi_slave_bid>),       //                    .bid
		.hps_0_f2h_axi_slave_bresp     (<connected-to-hps_0_f2h_axi_slave_bresp>),     //                    .bresp
		.hps_0_f2h_axi_slave_bvalid    (<connected-to-hps_0_f2h_axi_slave_bvalid>),    //                    .bvalid
		.hps_0_f2h_axi_slave_bready    (<connected-to-hps_0_f2h_axi_slave_bready>),    //                    .bready
		.hps_0_f2h_axi_slave_arid      (<connected-to-hps_0_f2h_axi_slave_arid>),      //                    .arid
		.hps_0_f2h_axi_slave_araddr    (<connected-to-hps_0_f2h_axi_slave_araddr>),    //                    .araddr
		.hps_0_f2h_axi_slave_arlen     (<connected-to-hps_0_f2h_axi_slave_arlen>),     //                    .arlen
		.hps_0_f2h_axi_slave_arsize    (<connected-to-hps_0_f2h_axi_slave_arsize>),    //                    .arsize
		.hps_0_f2h_axi_slave_arburst   (<connected-to-hps_0_f2h_axi_slave_arburst>),   //                    .arburst
		.hps_0_f2h_axi_slave_arlock    (<connected-to-hps_0_f2h_axi_slave_arlock>),    //                    .arlock
		.hps_0_f2h_axi_slave_arcache   (<connected-to-hps_0_f2h_axi_slave_arcache>),   //                    .arcache
		.hps_0_f2h_axi_slave_arprot    (<connected-to-hps_0_f2h_axi_slave_arprot>),    //                    .arprot
		.hps_0_f2h_axi_slave_arvalid   (<connected-to-hps_0_f2h_axi_slave_arvalid>),   //                    .arvalid
		.hps_0_f2h_axi_slave_arready   (<connected-to-hps_0_f2h_axi_slave_arready>),   //                    .arready
		.hps_0_f2h_axi_slave_aruser    (<connected-to-hps_0_f2h_axi_slave_aruser>),    //                    .aruser
		.hps_0_f2h_axi_slave_rid       (<connected-to-hps_0_f2h_axi_slave_rid>),       //                    .rid
		.hps_0_f2h_axi_slave_rdata     (<connected-to-hps_0_f2h_axi_slave_rdata>),     //                    .rdata
		.hps_0_f2h_axi_slave_rresp     (<connected-to-hps_0_f2h_axi_slave_rresp>),     //                    .rresp
		.hps_0_f2h_axi_slave_rlast     (<connected-to-hps_0_f2h_axi_slave_rlast>),     //                    .rlast
		.hps_0_f2h_axi_slave_rvalid    (<connected-to-hps_0_f2h_axi_slave_rvalid>),    //                    .rvalid
		.hps_0_f2h_axi_slave_rready    (<connected-to-hps_0_f2h_axi_slave_rready>),    //                    .rready
		.memory_mem_a                  (<connected-to-memory_mem_a>),                  //              memory.mem_a
		.memory_mem_ba                 (<connected-to-memory_mem_ba>),                 //                    .mem_ba
		.memory_mem_ck                 (<connected-to-memory_mem_ck>),                 //                    .mem_ck
		.memory_mem_ck_n               (<connected-to-memory_mem_ck_n>),               //                    .mem_ck_n
		.memory_mem_cke                (<connected-to-memory_mem_cke>),                //                    .mem_cke
		.memory_mem_cs_n               (<connected-to-memory_mem_cs_n>),               //                    .mem_cs_n
		.memory_mem_ras_n              (<connected-to-memory_mem_ras_n>),              //                    .mem_ras_n
		.memory_mem_cas_n              (<connected-to-memory_mem_cas_n>),              //                    .mem_cas_n
		.memory_mem_we_n               (<connected-to-memory_mem_we_n>),               //                    .mem_we_n
		.memory_mem_reset_n            (<connected-to-memory_mem_reset_n>),            //                    .mem_reset_n
		.memory_mem_dq                 (<connected-to-memory_mem_dq>),                 //                    .mem_dq
		.memory_mem_dqs                (<connected-to-memory_mem_dqs>),                //                    .mem_dqs
		.memory_mem_dqs_n              (<connected-to-memory_mem_dqs_n>),              //                    .mem_dqs_n
		.memory_mem_odt                (<connected-to-memory_mem_odt>),                //                    .mem_odt
		.memory_mem_dm                 (<connected-to-memory_mem_dm>),                 //                    .mem_dm
		.memory_oct_rzqin              (<connected-to-memory_oct_rzqin>),              //                    .oct_rzqin
		.hps_0_emac1_phy_txd_o         (<connected-to-hps_0_emac1_phy_txd_o>),         //         hps_0_emac1.phy_txd_o
		.hps_0_emac1_phy_txen_o        (<connected-to-hps_0_emac1_phy_txen_o>),        //                    .phy_txen_o
		.hps_0_emac1_phy_txer_o        (<connected-to-hps_0_emac1_phy_txer_o>),        //                    .phy_txer_o
		.hps_0_emac1_phy_rxdv_i        (<connected-to-hps_0_emac1_phy_rxdv_i>),        //                    .phy_rxdv_i
		.hps_0_emac1_phy_rxer_i        (<connected-to-hps_0_emac1_phy_rxer_i>),        //                    .phy_rxer_i
		.hps_0_emac1_phy_rxd_i         (<connected-to-hps_0_emac1_phy_rxd_i>),         //                    .phy_rxd_i
		.hps_0_emac1_phy_col_i         (<connected-to-hps_0_emac1_phy_col_i>),         //                    .phy_col_i
		.hps_0_emac1_phy_crs_i         (<connected-to-hps_0_emac1_phy_crs_i>),         //                    .phy_crs_i
		.hps_0_emac1_gmii_mdo_o        (<connected-to-hps_0_emac1_gmii_mdo_o>),        //                    .gmii_mdo_o
		.hps_0_emac1_gmii_mdo_o_e      (<connected-to-hps_0_emac1_gmii_mdo_o_e>),      //                    .gmii_mdo_o_e
		.hps_0_emac1_gmii_mdi_i        (<connected-to-hps_0_emac1_gmii_mdi_i>),        //                    .gmii_mdi_i
		.hps_0_emac1_ptp_pps_o         (<connected-to-hps_0_emac1_ptp_pps_o>),         //                    .ptp_pps_o
		.hps_0_emac1_ptp_aux_ts_trig_i (<connected-to-hps_0_emac1_ptp_aux_ts_trig_i>), //                    .ptp_aux_ts_trig_i
		.hps_0_h2f_loan_io_in          (<connected-to-hps_0_h2f_loan_io_in>),          //   hps_0_h2f_loan_io.in
		.hps_0_h2f_loan_io_out         (<connected-to-hps_0_h2f_loan_io_out>),         //                    .out
		.hps_0_h2f_loan_io_oe          (<connected-to-hps_0_h2f_loan_io_oe>)           //                    .oe
	);

